### ISSUE TITLE
Clarifications on using Rake

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Armour/sentence-classifier-based-on-word-similarity#1]
I studies with interest your code on github, during a research on using Rake for keyword extraction.

I couldn’t fully understand your aim in using “categories”, nor what the weights (? - I assume the numerical values are some kind of weights?) of each category meant.

I wonder if you could kindly explain the background, or possibly link any article (yours or from others) that you used as an inspiration.

Many thanks!

**Comment by Armour** [comment]
Hi, thanks for your feedback! This is actually a simple classifier that I implemented during one hackathon. The intention is to feed some sentences and figure out what is the main topic of those sentences (like two people talking about sports, then it should return sports with the highest value). Hope it helps :)
